# Generated by Django 4.0.4 on 2022-06-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adocao',
            old_name='valor',
            new_name='amount',
        ),
    ]
